-- MySQL Workbench Synchronization
-- Generated: 2026-03-08 23:40
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Patrick

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `mydb`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `mydb`.`TabFilha` 
DROP FOREIGN KEY `fk_TabFilha_TabMae`;

ALTER TABLE `mydb`.`TabMae` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
ADD COLUMN `NovaColuna` VARCHAR(40) GENERATED ALWAYS AS (`DescMae`) AFTER `DescMae`;

ALTER TABLE `mydb`.`TabFilha` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `mydb`.`TabFilha` 
ADD CONSTRAINT `fk_TabFilha_TabMae`
  FOREIGN KEY (`TabMae_CodTabMae`)
  REFERENCES `mydb`.`TabMae` (`CodTabMae`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
